// Define all modules and their actions (keys only — labels are translated in component)
export const MODULES_CONFIG = [
  { key: "dashboard", actions: ["view"] },
  { key: "staff", actions: ["view", "create", "edit", "delete"] },
  { key: "students", actions: ["view", "create", "edit", "delete"] },
  { key: "classes", actions: ["view", "create", "edit", "delete"] },
  { key: "academics", actions: ["view", "create", "edit", "delete", "publish"] },
  { key: "attendance", actions: ["view", "create", "edit", "delete"] },
  { key: "timetable", actions: ["view", "create", "edit", "delete"] },
  { key: "fees", actions: ["view", "create", "edit", "delete"] },
  { key: "payroll", actions: ["view", "create", "edit", "delete"] },
  { key: "messaging", actions: ["view", "create", "edit", "delete"] },
  { key: "reports", actions: ["view", "create", "edit", "delete"] },
  { key: "settings", actions: ["view", "create", "edit", "delete"] },
  { key: "front-desk", actions: ["view", "create", "edit", "delete"] },
  { key: "intake-forms", actions: ["view", "create", "edit", "delete"] },
  { key: "communication", actions: ["view", "create", "edit", "delete"] },
];

// Default permission templates — must match backend UserPermission.js exactly.
// Every module is listed explicitly so applying a template clears stale permissions.
export const PERMISSION_TEMPLATES = {
  admin: {
    name: "Admin",
    description: "Full access to all modules",
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true },
      staff: { view: true, create: true, edit: true, delete: true },
      students: { view: true, create: true, edit: true, delete: true },
      classes: { view: true, create: true, edit: true, delete: true },
      academics: { view: true, create: true, edit: true, delete: true, publish: true },
      attendance: { view: true, create: true, edit: true, delete: true },
      timetable: { view: true, create: true, edit: true, delete: true },
      fees: { view: true, create: true, edit: true, delete: true },
      payroll: { view: true, create: true, edit: true, delete: true },
      messaging: { view: true, create: true, edit: true, delete: true },
      reports: { view: true, create: true, edit: true, delete: true },
      settings: { view: true, create: true, edit: true, delete: true },
      "front-desk": { view: true, create: true, edit: true, delete: true },
      "intake-forms": { view: true, create: true, edit: true, delete: true },
    },
  },
  principal: {
    name: "Principal",
    description: "Full administrative access except settings deletion",
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true },
      staff: { view: true, create: true, edit: true, delete: true },
      students: { view: true, create: true, edit: true, delete: true },
      classes: { view: true, create: true, edit: true, delete: true },
      academics: { view: true, create: true, edit: true, delete: true, publish: true },
      attendance: { view: true, create: true, edit: true, delete: true },
      timetable: { view: true, create: true, edit: true, delete: true },
      fees: { view: true, create: true, edit: true, delete: true },
      payroll: { view: true, create: true, edit: true, delete: true },
      messaging: { view: true, create: true, edit: true, delete: true },
      reports: { view: true, create: true, edit: true, delete: true },
      settings: { view: true, create: true, edit: true, delete: false },
      "front-desk": { view: true, create: true, edit: true, delete: true },
      "intake-forms": { view: true, create: true, edit: true, delete: true },
    },
  },
  "vice-principal": {
    name: "Vice Principal",
    description: "Administrative access without delete permissions",
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: false },
      staff: { view: true, create: true, edit: true, delete: false },
      students: { view: true, create: true, edit: true, delete: false },
      classes: { view: true, create: true, edit: true, delete: false },
      academics: { view: true, create: true, edit: true, delete: false, publish: true },
      attendance: { view: true, create: true, edit: true, delete: false },
      timetable: { view: true, create: true, edit: true, delete: false },
      fees: { view: true, create: false, edit: false, delete: false },
      payroll: { view: true, create: false, edit: false, delete: false },
      messaging: { view: true, create: true, edit: true, delete: false },
      reports: { view: true, create: true, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: true, create: true, edit: true, delete: false },
      "intake-forms": { view: true, create: true, edit: true, delete: false },
    },
  },
  teacher: {
    name: "Teacher",
    description: "Access to classes, attendance, and students",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false },
      staff: { view: true, create: false, edit: false, delete: false },
      students: { view: true, create: false, edit: true, delete: false },
      classes: { view: true, create: false, edit: false, delete: false },
      academics: { view: true, create: true, edit: true, delete: false, publish: false },
      attendance: { view: true, create: true, edit: true, delete: false },
      timetable: { view: true, create: false, edit: false, delete: false },
      fees: { view: true, create: false, edit: false, delete: false },
      payroll: { view: false, create: false, edit: false, delete: false },
      messaging: { view: true, create: true, edit: true, delete: false },
      reports: { view: true, create: false, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: false, create: false, edit: false, delete: false },
      "intake-forms": { view: true, create: true, edit: true, delete: false },
    },
  },
  accountant: {
    name: "Accountant",
    description: "Access to fees and payroll",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false },
      staff: { view: true, create: false, edit: false, delete: false },
      students: { view: true, create: false, edit: false, delete: false },
      classes: { view: true, create: false, edit: false, delete: false },
      academics: { view: true, create: false, edit: false, delete: false, publish: false },
      attendance: { view: true, create: false, edit: false, delete: false },
      timetable: { view: false, create: false, edit: false, delete: false },
      fees: { view: true, create: true, edit: true, delete: true },
      payroll: { view: true, create: true, edit: true, delete: false },
      messaging: { view: true, create: true, edit: false, delete: false },
      reports: { view: true, create: false, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: false, create: false, edit: false, delete: false },
      "intake-forms": { view: true, create: false, edit: false, delete: false },
    },
  },
  librarian: {
    name: "Librarian",
    description: "Limited access for library management",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false },
      staff: { view: true, create: false, edit: false, delete: false },
      students: { view: true, create: false, edit: false, delete: false },
      classes: { view: true, create: false, edit: false, delete: false },
      academics: { view: true, create: false, edit: false, delete: false, publish: false },
      attendance: { view: true, create: false, edit: false, delete: false },
      timetable: { view: true, create: false, edit: false, delete: false },
      fees: { view: false, create: false, edit: false, delete: false },
      payroll: { view: false, create: false, edit: false, delete: false },
      messaging: { view: true, create: true, edit: false, delete: false },
      reports: { view: false, create: false, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: false, create: false, edit: false, delete: false },
      "intake-forms": { view: false, create: false, edit: false, delete: false },
    },
  },
  "lab-assistant": {
    name: "Lab Assistant",
    description: "Limited access for lab management",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false },
      staff: { view: true, create: false, edit: false, delete: false },
      students: { view: true, create: false, edit: false, delete: false },
      classes: { view: true, create: false, edit: false, delete: false },
      academics: { view: true, create: false, edit: false, delete: false, publish: false },
      attendance: { view: true, create: false, edit: false, delete: false },
      timetable: { view: true, create: false, edit: false, delete: false },
      fees: { view: false, create: false, edit: false, delete: false },
      payroll: { view: false, create: false, edit: false, delete: false },
      messaging: { view: true, create: true, edit: false, delete: false },
      reports: { view: false, create: false, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: false, create: false, edit: false, delete: false },
      "intake-forms": { view: false, create: false, edit: false, delete: false },
    },
  },
  receptionist: {
    name: "Receptionist",
    description: "Basic access for front desk operations",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false },
      staff: { view: true, create: false, edit: false, delete: false },
      students: { view: true, create: true, edit: true, delete: false },
      classes: { view: true, create: false, edit: false, delete: false },
      academics: { view: true, create: false, edit: false, delete: false, publish: false },
      attendance: { view: true, create: false, edit: false, delete: false },
      timetable: { view: false, create: false, edit: false, delete: false },
      fees: { view: true, create: false, edit: false, delete: false },
      payroll: { view: false, create: false, edit: false, delete: false },
      messaging: { view: true, create: true, edit: false, delete: false },
      reports: { view: false, create: false, edit: false, delete: false },
      settings: { view: false, create: false, edit: false, delete: false },
      "front-desk": { view: true, create: true, edit: true, delete: false },
      "intake-forms": { view: true, create: true, edit: true, delete: false },
    },
  },
};
