export const DEPARTMENTS = [
  "Science",
  "Mathematics",
  "Languages",
  "Social Studies",
  "Commerce",
  "Arts",
  "Physical Education",
  "IT/Computer",
  "Library",
  "Administration",
  "Accounts",
  "Management",
  "Counseling",
  "Special Education",
  "Sports",
  "Others",
];

export const DEGREE_OPTIONS = [
  { label: "B.Ed", value: "B.Ed" },
  { label: "M.Ed", value: "M.Ed" },
  { label: "PhD", value: "PhD" },
  { label: "B.Sc", value: "B.Sc" },
  { label: "M.Sc", value: "M.Sc" },
  { label: "B.A", value: "B.A" },
  { label: "M.A", value: "M.A" },
  { label: "B.Com", value: "B.Com" },
  { label: "M.Com", value: "M.Com" },
  { label: "MBA", value: "MBA" },
  { label: "B.Tech", value: "B.Tech" },
  { label: "M.Tech", value: "M.Tech" },
  { label: "Other", value: "Other" },
];
