import { parseDate } from "@internationalized/date";
import { Input, Select, SelectItem, Chip, Switch, DatePicker } from "@heroui/react";
import { Lock } from "lucide-react";
import { staffTypes, shiftOptions } from "./constants";
import { useTranslation } from "react-i18next";

const StepJobDetails = ({
  formData,
  errors,
  updateField,
  departments,
  availableClasses,
  loadingClasses,
}) => {
  const { t } = useTranslation();

  return (
    <div className="space-y-6 animate-fade-in text-left">
      <div className="space-y-4">
        <label className="text-sm font-semibold text-default-900 block">{t('pages.jobDetails')}</label>

        {/* Role Selection - Multiple */}
        <div className="space-y-2">
          <Select
            aria-label={t('aria.inputs.staffRoles')}
            label={t('pages.staffRoles1')}
            labelPlacement="outside"
            placeholder={t('pages.selectOneOrMoreRoles')}
            selectedKeys={new Set(formData.staffType ? (Array.isArray(formData.staffType) ? formData.staffType : [formData.staffType]) : [])}
            onSelectionChange={(keys) => {
              const selectedRoles = Array.from(keys);
              updateField("staffType", selectedRoles.length > 0 ? selectedRoles : []);
            }}
            selectionMode="multiple"
            variant="bordered"
            radius="sm"
            isRequired
            classNames={{ trigger: "bg-default-50 dark:bg-default-100/50 border-1 border-default-200 hover:border-default-300 h-10" }}
            isInvalid={!!errors.staffType}
            errorMessage={errors.staffType}
          >
            {staffTypes.map((role) => (
              <SelectItem key={role}>{role}</SelectItem>
            ))}
          </Select>

          {/* Selected Roles Display */}
          {formData.staffType && formData.staffType.length > 0 && (
            <div className="flex flex-wrap gap-2 pt-1">
              {formData.staffType.map((role, idx) => (
                <Chip
                  key={role}
                  size="sm"
                  variant="flat"
                  color="primary"
                  onClose={() => {
                    const updatedRoles = formData.staffType.filter((_, i) => i !== idx);
                    updateField("staffType", updatedRoles);
                  }}
                >
                  {role}
                </Chip>
              ))}
            </div>
          )}
          <p className="text-xs text-default-500">{t('pages.selectAllApplicableRolesForThisStaffMember')}</p>
        </div>

        <div className="space-y-4">
          <Input
            label="Staff ID / Number"
            labelPlacement="outside"
            placeholder={t('pages.autoGenerated')}
            value={formData.staffNumber}
            isReadOnly
            variant="bordered"
            radius="sm"
            startContent={<Lock size={14} className="text-default-400" />}
            classNames={{ inputWrapper: "bg-default-100 dark:bg-default-100/50 border-1 border-default-200 h-10 cursor-not-allowed opacity-70" }}
            description={formData.staffNumber ? "Staff ID" : "Will be auto-generated by the server"}
          />

          <Select
            label={t('pages.department1')}
            labelPlacement="outside"
            placeholder={t('pages.selectDepartment')}
            selectedKeys={formData.department ? [formData.department] : []}
            onSelectionChange={(keys) => updateField("department", Array.from(keys)[0])}
            variant="bordered"
            radius="sm"
            isRequired
            isInvalid={!!errors.department}
            errorMessage={errors.department}
            classNames={{ trigger: "bg-default-50 dark:bg-default-100/50 border-1 border-default-200 hover:border-default-300 h-10" }}
          >
            {departments.map((dept) => (
              <SelectItem key={dept}>{dept}</SelectItem>
            ))}
          </Select>

          <div className="grid grid-cols-2 gap-4">
            <DatePicker
              aria-label="Join Date"
              label="Join Date"
              labelPlacement="outside"
              value={(() => {
                if (!formData.joinDate) return null;
                try {
                  const dateStr = formData.joinDate.split('T')[0];
                  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return parseDate(dateStr);
                  return null;
                } catch { return null; }
              })()}
              onChange={(date) => {
                if (!date) { updateField("joinDate", ""); return; }
                try { updateField("joinDate", date.toString()); } catch { updateField("joinDate", ""); }
              }}
              variant="bordered"
              radius="sm"
              showMonthAndYearPickers
              portalContainer={document.body}
              className="w-full"
              classNames={{ inputWrapper: "bg-default-50 dark:bg-default-100/50 border-1 border-default-200 hover:border-default-300 h-10" }}
            />
            <Select
              label="Shift"
              labelPlacement="outside"
              placeholder="Select shift"
              selectedKeys={formData.shift ? [formData.shift] : []}
              onSelectionChange={(keys) => updateField("shift", Array.from(keys)[0])}
              variant="bordered"
              radius="sm"
              classNames={{ trigger: "bg-default-50 dark:bg-default-100/50 border-1 border-default-200 hover:border-default-300 h-10" }}
            >
              {shiftOptions.map((s) => (
                <SelectItem key={s}>{s}</SelectItem>
              ))}
            </Select>
          </div>
        </div>

        {(Array.isArray(formData.staffType) ? formData.staffType.includes("Teacher") : formData.staffType === "Teaching") && (
          <div className="space-y-4 pt-4 border-t border-dashed border-default-200">
            {/* Show Class Teacher First */}
            <div className="flex flex-col gap-2 p-4 border border-default-200 rounded-xl bg-default-50/50">
              <div className="flex justify-between items-center">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-default-900">{t('pages.asClassTeacher')}</span>
                  <span className="text-xs text-default-500">{t('pages.isThisStaffMemberAClassTeacher')}</span>
                </div>
                <Switch
                  size="sm"
                  isSelected={formData.isClassTeacher}
                  onValueChange={(v) => updateField("isClassTeacher", v)}
                />
              </div>

              {formData.isClassTeacher && (
                <Select
                  className="mt-2"
                  label={t('pages.selectClass1')}
                  placeholder={t('staff.form.selectClassPlaceholder')}
                  isLoading={loadingClasses}
                  selectedKeys={formData.classTeacherOf ? [formData.classTeacherOf] : []}
                  onSelectionChange={(keys) => updateField("classTeacherOf", Array.from(keys)[0])}
                  variant="bordered"
                  radius="sm"
                  size="sm"
                  isDisabled={loadingClasses}
                  classNames={{ trigger: "bg-white dark:bg-default-100 border-1 border-default-200" }}
                >
                  {availableClasses.map((cls) => (
                    <SelectItem key={cls.id}>{cls.displayName}</SelectItem>
                  ))}
                </Select>
              )}
            </div>

            {/* Then Show Assign Classes for subject teaching */}
            <div className="space-y-1.5">
              <label className="text-sm font-semibold text-default-900">{t('pages.assignClassesForSubjectTeaching')}</label>
              <Select
                selectionMode="multiple"
                placeholder={t('staff.form.selectClassesPlaceholder')}
                isLoading={loadingClasses}
                selectedKeys={new Set(formData.assignedClasses)}
                onSelectionChange={(keys) => updateField("assignedClasses", Array.from(keys))}
                variant="bordered"
                radius="sm"
                isDisabled={loadingClasses}
                classNames={{ trigger: "bg-default-50 dark:bg-default-100/50 border-1 border-default-200 hover:border-default-300 min-h-unit-10" }}
              >
                {availableClasses.map((cls) => (
                  <SelectItem key={cls.id}>{cls.displayName}</SelectItem>
                ))}
              </Select>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default StepJobDetails;
