import { request } from '../../services/api.js';
import { useState, useEffect } from "react";
import { Card, CardBody, CardHeader, Input, Switch, Button, Divider, Select, SelectItem, Skeleton } from "@heroui/react";
import { Save, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { useTranslation } from 'react-i18next';
import logger from '../../utils/logger';


export default function StaffIdSettings() {
  const { t } = useTranslation();
  const [config, setConfig] = useState(null);

  const [preview, setPreview] = useState("");
  const [saving, setSaving] = useState(false);
  const [initialLoading, setInitialLoading] = useState(true);

  useEffect(() => {
    // Load current configuration
    loadConfig();
  }, []);

  useEffect(() => {
    // Update preview whenever config changes
    updatePreview();
  }, [config]);

  const DEFAULT_CONFIG = {
    prefix: "EMP",
    startingNumber: 1,
    digits: 3,
    includeYear: false,
    separator: ""
  };

  const loadConfig = async () => {
    try {
      const data = await request('/staff-id-config');
      setConfig({
        prefix: data.prefix || 'EMP',
        startingNumber: data.startingNumber || 1,
        digits: data.digits || 3,
        includeYear: data.includeYear || false,
        separator: data.separator || ''
      });
    } catch (error) {
      logger.error("Error loading config:", error);
      setConfig(DEFAULT_CONFIG);
      toast.error(t('toast.error.failedToLoadConfiguration'));
    } finally {
      setInitialLoading(false);
    }
  };

  const updatePreview = () => {
    if (!config) return;
    const { prefix, startingNumber, digits, includeYear, separator } = config;
    const paddedNumber = String(startingNumber).padStart(digits, '0');
    const year = new Date().getFullYear();

    let previewId = prefix;
    if (separator) previewId += separator;
    if (includeYear) previewId += year + (separator || "");
    previewId += paddedNumber;

    setPreview(previewId);
  };

  // AUDIT-134: Added validation before save
  const handleSave = async () => {
    if (!config.prefix?.trim()) { toast.error('Prefix is required'); return; }
    if (config.digits < 1 || config.digits > 10) { toast.error('Digits must be between 1 and 10'); return; }
    if (config.startingNumber < 0) { toast.error('Starting number cannot be negative'); return; }
    setSaving(true);
    try {
      await request('/staff-id-config', {
        method: 'PUT',
        body: JSON.stringify(config)
      });

      toast.success(t('toast.success.staffIdConfigurationSavedSuccessfully'));
    } catch (error) {
      logger.error("Error saving config:", error);
      toast.error(t('toast.error.failedToSaveConfiguration'));
    } finally {
      setSaving(false);
    }
  };

  const handleReset = () => {
    setConfig({ ...DEFAULT_CONFIG });
    toast.success(t('toast.success.configurationResetToDefaults'));
  };

  if (initialLoading) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-fg">{t('pages.staffIdConfiguration')}</h2>
          <p className="text-fg-muted mt-1">{t('pages.configureHowStaffIdsAreGeneratedForNewStaffMembers')}</p>
        </div>
        <Card shadow="none" className="border border-border-token">
          <CardHeader className="px-6 py-4">
            <div className="space-y-2 w-full">
              <Skeleton className="h-5 w-48 rounded-lg" />
              <Skeleton className="h-4 w-72 rounded-lg" />
            </div>
          </CardHeader>
          <Divider />
          <CardBody className="px-6 py-6 space-y-6">
            <Skeleton className="h-24 w-full rounded-lg" />
            <Skeleton className="h-14 w-full rounded-lg" />
            <Skeleton className="h-14 w-full rounded-lg" />
            <Skeleton className="h-14 w-full rounded-lg" />
            <Skeleton className="h-14 w-full rounded-lg" />
            <Skeleton className="h-14 w-full rounded-lg" />
          </CardBody>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-fg">{t('pages.staffIdConfiguration')}</h2>
        <p className="text-fg-muted mt-1">{t('pages.configureHowStaffIdsAreGeneratedForNewStaffMembers')}</p>
      </div>

      <Card shadow="none" className="border border-border-token">
        <CardHeader className="flex justify-between items-center px-6 py-4">
          <div>
            <h3 className="text-lg font-semibold text-fg">{t('pages.iDFormatSettings')}</h3>
            <p className="text-sm text-fg-muted mt-1">{t('pages.customizeTheFormatOfAutoGeneratedStaffIds')}</p>
          </div>
        </CardHeader>
        <Divider />
        <CardBody className="px-6 py-6 space-y-6">
          {/* Preview */}
          <div className="bg-primary-50 border border-primary-200 rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-fg-muted">{t('pages.preview1')}</p>
                <p className="text-2xl font-bold text-primary-600 mt-1">{preview}</p>
                <p className="text-xs text-fg-muted mt-1">{t('pages.thisIsHowTheNextStaffIdWillLook')}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-fg-muted">{t('pages.nextId')}</p>
                <p className="text-lg font-semibold text-fg">{preview}</p>
              </div>
            </div>
          </div>

          {/* Prefix */}
          <Input
            label={t('pages.prefix')}
            placeholder={t('settings.staffIdPrefixPlaceholder')}
            value={config.prefix}
            onChange={(e) => setConfig({ ...config, prefix: e.target.value.toUpperCase() })}
            description="The prefix that appears at the start of the staff ID"
            variant="bordered"
          />

          {/* Separator */}
          <Select
            label={t('pages.separator')}
            placeholder={t('pages.selectSeparator')}
            selectedKeys={config.separator !== undefined ? [config.separator] : [""]}
            onSelectionChange={(keys) => setConfig({ ...config, separator: Array.from(keys)[0] ?? "" })}
            description="Character to separate parts of the ID"
            variant="bordered"
          >
            <SelectItem key="" value="">{t('pages.none1')}</SelectItem>
            <SelectItem key="-" value="-">{t('pages.hyphen')}</SelectItem>
            <SelectItem key="/" value="/">Slash (/)</SelectItem>
            <SelectItem key="_" value="_">Underscore (_)</SelectItem>
          </Select>

          {/* Include Year */}
          <div className="flex items-center justify-between p-4 bg-surface-2 rounded-lg">
            <div>
              <p className="font-medium text-fg">{t('pages.includeYear')}</p>
              <p className="text-sm text-fg-muted">{t('pages.addCurrentYearToTheStaffId')}</p>
            </div>
            <Switch
              isSelected={config.includeYear}
              onValueChange={(value) => setConfig({ ...config, includeYear: value })}
              color="primary"
            />
          </div>

          {/* Starting Number */}
          <Input
            type="number"
            label={t('pages.startingNumber')}
            placeholder={t('settings.startingNumberPlaceholder')}
            value={config.startingNumber}
            onChange={(e) => setConfig({ ...config, startingNumber: parseInt(e.target.value) || 1 })}
            description="The number to start counting from"
            variant="bordered"
            min={1}
          />

          {/* Number of Digits */}
          <Input
            type="number"
            label={t('pages.numberOfDigits')}
            placeholder={t('settings.digitsPlaceholder')}
            value={config.digits}
            onChange={(e) => setConfig({ ...config, digits: parseInt(e.target.value) || 3 })}
            description="How many digits to use for the number (with leading zeros)"
            variant="bordered"
            min={1}
            max={6}
          />

          {/* Examples */}
          <div className="bg-surface-2 rounded-lg p-4 space-y-2">
            <p className="text-sm font-medium text-fg">{t('pages.examplesWithCurrentSettings')}</p>
            <div className="space-y-1">
              <p className="text-sm text-fg-muted">• First staff: <span className="font-mono font-semibold">{preview}</span></p>
              <p className="text-sm text-fg-muted">• Second staff: <span className="font-mono font-semibold">
                {config.prefix}{config.separator}{config.includeYear ? new Date().getFullYear() + (config.separator || "") : ""}{String(config.startingNumber + 1).padStart(config.digits, '0')}
              </span></p>
              <p className="text-sm text-fg-muted">• Third staff: <span className="font-mono font-semibold">
                {config.prefix}{config.separator}{config.includeYear ? new Date().getFullYear() + (config.separator || "") : ""}{String(config.startingNumber + 2).padStart(config.digits, '0')}
              </span></p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4">
            <Button
              color="primary"
              startContent={<Save size={18} />}
              onPress={handleSave}
              isLoading={saving}
            >
              Save Configuration
            </Button>
            <Button
              variant="flat"
              startContent={<RefreshCw size={18} />}
              onPress={handleReset}
            >
              Reset to Defaults
            </Button>
          </div>
        </CardBody>
      </Card>

      {/* Warning Card */}
      <Card shadow="none" className="border border-warning-200 bg-warning-50">
        <CardBody className="px-6 py-4">
          <div className="flex gap-3">
            <div className="text-warning-600 mt-0.5">⚠️</div>
            <div>
              <p className="font-semibold text-warning-900">{t('pages.importantNotes')}</p>
              <ul className="text-sm text-warning-700 mt-2 space-y-1 list-disc list-inside">
                <li>{t('pages.changesWillOnlyAffectNewStaffMembersAddedAfterSaving')}</li>
                <li>{t('pages.existingStaffIdsWillNotBeModified')}</li>
                <li>{t('pages.makeSureTheFormatIsUniqueAndEasyToIdentify')}</li>
                <li>{t('pages.theSystemWillAutomaticallyIncrementTheNumberForEachNewStaff')}</li>
              </ul>
            </div>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
