import { request } from '../../services/api.js';
import { useState, useEffect } from "react";
import { Card, CardBody, CardHeader, Input, Switch, Button, Divider, Select, SelectItem } from "@heroui/react";
import { Save, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { useTranslation } from 'react-i18next';

export default function StaffIdSettings() {
  const { t } = useTranslation();
  const [config, setConfig] = useState({
    prefix: "EMP",
    startingNumber: 1,
    digits: 3,
    includeYear: false,
    separator: ""
  });

  const [preview, setPreview] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Load current configuration
    loadConfig();
  }, []);

  useEffect(() => {
    // Update preview whenever config changes
    updatePreview();
  }, [config]);

  const loadConfig = async () => {
    try {
      const data = await request('/staff-id-config');
      setConfig({
        prefix: data.prefix || 'EMP',
        startingNumber: data.startingNumber || 1,
        digits: data.digits || 3,
        includeYear: data.includeYear || false,
        separator: data.separator || ''
      });
    } catch (error) {
      console.error("Error loading config:", error);
      toast.error(t('toast.error.failedToLoadConfiguration'));
    }
  };

  const updatePreview = () => {
    const { prefix, startingNumber, digits, includeYear, separator } = config;
    const paddedNumber = String(startingNumber).padStart(digits, '0');
    const year = new Date().getFullYear();
    
    let previewId = prefix;
    if (separator) previewId += separator;
    if (includeYear) previewId += year + (separator || "");
    previewId += paddedNumber;
    
    setPreview(previewId);
  };

  const handleSave = async () => {
    setLoading(true);
    try {
      await request('/staff-id-config', {
        method: 'PUT',
        body: JSON.stringify(config)
      });
      
      toast.success(t('toast.success.staffIdConfigurationSavedSuccessfully'));
    } catch (error) {
      console.error("Error saving config:", error);
      toast.error(t('toast.error.failedToSaveConfiguration'));
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setConfig({
      prefix: "EMP",
      startingNumber: 1,
      digits: 3,
      includeYear: false,
      separator: ""
    });
    toast.success(t('toast.success.configurationResetToDefaults'));
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-default-900">{t('pages.staffIdConfiguration')}</h2>
        <p className="text-default-500 mt-1">{t('pages.configureHowStaffIdsAreGeneratedForNewStaffMembers')}</p>
      </div>

      <Card shadow="none" className="border border-default-200">
        <CardHeader className="flex justify-between items-center px-6 py-4">
          <div>
            <h3 className="text-lg font-semibold text-default-900">{t('pages.iDFormatSettings')}</h3>
            <p className="text-sm text-default-500 mt-1">{t('pages.customizeTheFormatOfAutoGeneratedStaffIds')}</p>
          </div>
        </CardHeader>
        <Divider />
        <CardBody className="px-6 py-6 space-y-6">
          {/* Preview */}
          <div className="bg-primary-50 border border-primary-200 rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-default-600">{t('pages.preview1')}</p>
                <p className="text-2xl font-bold text-primary-600 mt-1">{preview}</p>
                <p className="text-xs text-default-500 mt-1">{t('pages.thisIsHowTheNextStaffIdWillLook')}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-default-500">{t('pages.nextId')}</p>
                <p className="text-lg font-semibold text-default-900">{preview}</p>
              </div>
            </div>
          </div>

          {/* Prefix */}
          <Input
            label={t('pages.prefix')}
            placeholder="e.g., EMP, STF, STAFF"
            value={config.prefix}
            onChange={(e) => setConfig({ ...config, prefix: e.target.value.toUpperCase() })}
            description="The prefix that appears at the start of the staff ID"
            variant="bordered"
          />

          {/* Separator */}
          <Select
            label={t('pages.separator')}
            placeholder={t('pages.selectSeparator')}
            selectedKeys={config.separator !== undefined ? [config.separator] : [""]}
            onSelectionChange={(keys) => setConfig({ ...config, separator: Array.from(keys)[0] ?? "" })}
            description="Character to separate parts of the ID"
            variant="bordered"
          >
            <SelectItem key="" value="">{t('pages.none1')}</SelectItem>
            <SelectItem key="-" value="-">{t('pages.hyphen')}</SelectItem>
            <SelectItem key="/" value="/">Slash (/)</SelectItem>
            <SelectItem key="_" value="_">Underscore (_)</SelectItem>
          </Select>

          {/* Include Year */}
          <div className="flex items-center justify-between p-4 bg-default-50 rounded-lg">
            <div>
              <p className="font-medium text-default-900">{t('pages.includeYear')}</p>
              <p className="text-sm text-default-500">{t('pages.addCurrentYearToTheStaffId')}</p>
            </div>
            <Switch
              isSelected={config.includeYear}
              onValueChange={(value) => setConfig({ ...config, includeYear: value })}
              color="primary"
            />
          </div>

          {/* Starting Number */}
          <Input
            type="number"
            label={t('pages.startingNumber')}
            placeholder="1"
            value={config.startingNumber}
            onChange={(e) => setConfig({ ...config, startingNumber: parseInt(e.target.value) || 1 })}
            description="The number to start counting from"
            variant="bordered"
            min={1}
          />

          {/* Number of Digits */}
          <Input
            type="number"
            label={t('pages.numberOfDigits')}
            placeholder="3"
            value={config.digits}
            onChange={(e) => setConfig({ ...config, digits: parseInt(e.target.value) || 3 })}
            description="How many digits to use for the number (with leading zeros)"
            variant="bordered"
            min={1}
            max={6}
          />

          {/* Examples */}
          <div className="bg-default-50 rounded-lg p-4 space-y-2">
            <p className="text-sm font-medium text-default-700">{t('pages.examplesWithCurrentSettings')}</p>
            <div className="space-y-1">
              <p className="text-sm text-default-600">• First staff: <span className="font-mono font-semibold">{preview}</span></p>
              <p className="text-sm text-default-600">• Second staff: <span className="font-mono font-semibold">
                {config.prefix}{config.separator}{config.includeYear ? new Date().getFullYear() + (config.separator || "") : ""}{String(config.startingNumber + 1).padStart(config.digits, '0')}
              </span></p>
              <p className="text-sm text-default-600">• Third staff: <span className="font-mono font-semibold">
                {config.prefix}{config.separator}{config.includeYear ? new Date().getFullYear() + (config.separator || "") : ""}{String(config.startingNumber + 2).padStart(config.digits, '0')}
              </span></p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4">
            <Button
              color="primary"
              startContent={<Save size={18} />}
              onPress={handleSave}
              isLoading={loading}
            >
              Save Configuration
            </Button>
            <Button
              variant="flat"
              startContent={<RefreshCw size={18} />}
              onPress={handleReset}
            >
              Reset to Defaults
            </Button>
          </div>
        </CardBody>
      </Card>

      {/* Warning Card */}
      <Card shadow="none" className="border border-warning-200 bg-warning-50">
        <CardBody className="px-6 py-4">
          <div className="flex gap-3">
            <div className="text-warning-600 mt-0.5">⚠️</div>
            <div>
              <p className="font-semibold text-warning-900">{t('pages.importantNotes')}</p>
              <ul className="text-sm text-warning-700 mt-2 space-y-1 list-disc list-inside">
                <li>{t('pages.changesWillOnlyAffectNewStaffMembersAddedAfterSaving')}</li>
                <li>{t('pages.existingStaffIdsWillNotBeModified')}</li>
                <li>{t('pages.makeSureTheFormatIsUniqueAndEasyToIdentify')}</li>
                <li>{t('pages.theSystemWillAutomaticallyIncrementTheNumberForEachNewStaff')}</li>
              </ul>
            </div>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
